### ISSUE TITLE
Error when matching rabbits: by_subplan: planner_multi_avail_during returned -1

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-sched#1260]
With this [JGF](https://github.com/user-attachments/files/16435134/tioga-JGF.json) and the jobspec below, I get the following error even though the match succeeds:

```yaml
version: 9999
resources:
  - type: slot
    count: 2
    label: default
    with:
    - type: ssd
      count: 1
    - type: node
      exclusive: true
      count: 1
      with:
      - type: slot
        label: task
        count: 1
        with:
        - type: core
          count: 1
# a comment
attributes:
  system:
    duration: 3600
tasks:
  - command: [ "app" ]
    slot: task
    count:
      per_slot: 1
```

```
ERROR: by_subplan: planner_multi_avail_during returned -1.
Invalid argument.
by_subplan: planner_multi_avail_during returned -1.
Invalid argument.
by_subplan: planner_multi_avail_during returned -1.
Invalid argument.
by_subplan: planner_multi_avail_during returned -1.
Invalid argument.
by_subplan: planner_multi_avail_during returned -1.
Invalid argument.
by_subplan: planner_multi_avail_during returned -1.
Invalid argument.
by_subplan: planner_multi_avail_during returned -1.
Invalid argument.
by_subplan: planner_multi_avail_during returned -1.
Invalid argument.
by_subplan: planner_multi_avail_during returned -1.
Invalid argument.
by_subplan: planner_multi_avail_during returned -1.
[snip -- continues for many many lines]
```

**Comment by milroy** [comment]
I am able to reproduce this issue with a slightly simpler jobspec (note slot count of `1`):

```yaml
version: 9999
resources:
  - type: slot
    count: 1
    label: default
    with:
    - type: ssd
      count: 1
    - type: node
      exclusive: true
      count: 1
      with:
      - type: slot
        label: task
        count: 1
        with:
        - type: core
          count: 1
# a comment
attributes:
  system:
    duration: 3600
tasks:
  - command: [ "app" ]
    slot: task
    count:
      per_slot: 1
```
And I have a fix. 

The only remaining problem is I can't reproduce this issue with the test JGF (`t/data/resource/jgfs/issue1284.json`), with the reduced slot count. @jameshcorbett can you make me a smaller test JGF based on the tioga graph attached to this issue? Also, do you have any ideas why this won't reproduce on `issue1284.json`?
