### ISSUE TITLE
Allocation fails for resources with uncapped (or large max) ranges below slot with count > 1

### ISSUE THREAD

**Issue by sam-maloney** [flux-framework/flux-sched#1373]
Not urgent, but thought I would document this for future reference.

A relatively simple seeming resource request such as the following currently fails to allocate, with the error: `"type":"alloc","severity":0,"note":"alloc denied due to type=\"unsatisfiable\""`

```yaml=
resources:
  - type: node
    count: 1
    with:
      - type: slot
        count: 2
        label: task
        with:
          - type: core
            count:
              min: 1
```

I think this appears to happen because the virtual `slot` resource is treated differently, so the scheduler first drops to the lower core level and resolves the uncapped range request to be the full number of cores available in the node, rather than limiting it to `cores_per_node/slot_count`. This then gets multiplied by `slot_count` for the overall request, which is of course unsatisfiable (the problem will occur for any `max > cores_per_node/slot_count` when `slot_count > 1`).

Not exactly the same, but this perhaps has some connection to discussions such as flux-framework/rfc#452 about how the current treatment of slots is problematic for moldable/malleable jobspec.
