### ISSUE TITLE
Building flux-sched with cuda on Perlmutter using Spack

### ISSUE THREAD

**Issue by BagchiS6** [flux-framework/flux-sched#1374]
I am trying to build flux on Perlmutter through spack.  My environment file `spack.yaml` looks like the following. This leads to failures related to `libcudart.so` not found , while (c.f. `spack.yaml` attached) should correspond to the correct paths). 
Any primers on setting up installing a working flux-sched with cuda support on Perlmutter would be helpful. 
```
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs:
  - python@3.11
  - ninja ^python@3.11.11
  - cuda@12.4
  - flux-sched+cuda
  view: true
  concretizer:
    unify: true
  packages:
    cuda:
      externals:
      - spec: cuda@12.4.131
        prefix: /opt/nvidia/hpc_sdk/Linux_x86_64/24.5/cuda/12.4
    gcc:
      externals:
      - spec: gcc@12.2.0 languages:='c,c++,fortran'
        prefix: /opt/cray/pe/gcc/12.2.0
        extra_attributes:
          compilers:
            c: /opt/cray/pe/gcc/12.2.0/bin/gcc
            cxx: /opt/cray/pe/gcc/12.2.0/bin/g++
            fortran: /opt/cray/pe/gcc/12.2.0/bin/gfortran
```
