### ISSUE TITLE
resource: equivalent resource requests result in different behaviors

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#410]
When writing tests for #385, I noticed that for two "equivalent" resource requests, one fails and one succeeds.

Reproducer:
```
$ ./resource-query -X ~/Repositories/flux-framework/flux-sched/t/data/hwloc-data/004N/exclusive/04-brokers/0.xml -p ALL:pu
resource-query> match allocate flux-sched/t/data/resource/jobspecs/basics/test009.yaml
```
Note: I'm using the hwloc from `004N` because there are 2 sockets per node (unlike `001N` which has only 1 socket per node).

When I use this jobspec:
```yaml
version: 1                                                                                                                                                                                                                                                                               
resources:                                                                                                                                                                                                                                                                               
  - type: slot                                                                                                                                                                                                                                                                           
    count: 2                                                                                                                                                                                                                                                                             
    label: default                                                                                                                                                                                                                                                                       
    with:                                                                                                                                                                                                                                                                                
      - type: socket                                                                                                                                                                                                                                                                     
        count: 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
tasks:
  - command: app                                                                                                                                                                                                                                                                         
    slot: default                                                                                                                                                                                                                                                                        
    count:                                                                                                                                                                                                                                                                               
      per_slot: 1 
```
I get this:
```
      ------------socket0[1:x]
      ---------numanode0[1:s]
      ------------socket1[1:x]
      ---------numanode1[1:s]
      ------cab1234[1:s]
      ---cluster0[1:s]
INFO: =============================
INFO: JOBID=1
INFO: RESOURCES=ALLOCATED
INFO: SCHEDULED AT=Now
INFO: =============================
```

I when use this jobspec (on a fresh invocation of the command, so there are no allocations/reservations):
```yaml
version: 1                                                                                                                                                                                                                                                                               
resources:                                                                                                                                                                                                                                                                               
  - type: slot                                                                                                                                                                                                                                                                           
    count: 1                                                                                                                                                                                                                                                                             
    label: default                                                                                                                                                                                                                                                                       
    with:                                                                                                                                                                                                                                                                                
      - type: socket                                                                                                                                                                                                                                                                     
        count: 2
                                                                                                                                                                                                                                                                    
tasks:
  - command: app                                                                                                                                                                                                                                                                         
    slot: default                                                                                                                                                                                                                                                                        
    count:                                                                                                                                                                                                                                                                               
      per_slot: 1 
```
I get this:
```
INFO: =============================
INFO: No matching resources found
INFO: JOBID=1
INFO: =============================
```

I may be under-thinking this, but my thought process is that both of these jobspecs are ultimately requesting 2 sockets for the job and 2 sockets exist on the system.  So I'm not sure why one succeeds and the other fails.
