### ISSUE TITLE
Fix issues discovered during our evaluation for ASPLOS WORD submission

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#447]
As I was running the experiments for ASPLOS WORD workshop, I found that the number of vertices populated to the graph data store within the resource-matching service appeared to be twice as many! It is highly likely that the problem was previously identified by @SteVwonder in https://github.com/flux-framework/flux-sched/blob/master/resource/generators/gen.cpp#L203

I will run my WORD experiments with this line commented out and if there is not side effect, I will add a fix for this nasty bug.

**Comment by dongahn** [comment]
I just changed the title to capture all the issues discovered during an research evaluation. I didn't want to create individual tickets for each issue.

**Comment by dongahn** [comment]
Additional issues:
- Add a performance metric for graph load time under the `--elapse-time` option of `resource-query`. I also found there is a bug in this option as well.
- There seem to be some issues in dealing with `slot`. For example, there are cases where `resource-query` could not match resources when a `slot` is absence etc.

**Comment by SteVwonder** [comment]
Sorry for not following through with my own `TODO` 🤦‍♂️

**Comment by dongahn** [comment]
@SteVwonder: Hmmm I didn't know you had other TODOs though :-). Honestly I think only thing we need would be to add a bit more references and we will be in a very good shape. Have a great weekend and have a safe trip!

**Comment by dongahn** [comment]
> - There seem to be some issues in dealing with slot. For example, there are cases where resource-query could not match resources when a slot is absence etc.

`resource-query` matches okay with the first jobspec below but doesn't match with the second job spec. 

```yaml
version: 1
resources:
    - type: cluster
      count: 1
      with:
        - type: rack
          count: 1
          with:
            - type: node
              count: 1
              with:
                  - type: slot
                    count: 1
                    label: default
                    with:
                      - type: socket
                        count: 1
                        with:
                          - type: core
                            count: 1
```

```yaml
version: 1
resources:
    - type: cluster
      count: 1
      with:
        - type: rack
          count: 1
          with:
            - type: node
              count: 1
              with:
                - type: socket
                  count: 1
                  with:
                    - type: core
                      count: 1
```

It turns out the issue with the second spec was that it has no exclusive resource request in it, which then breaks `resource-query`'s  update scheme. 

```yaml
                  with:
                    - type: core
                      count: 1
                      exclusive: true
```

I confirmed that if the spec has `exclusive: true` for `core`, then the match works. 

I realized we discussed this before. To avoid a situation like we need a sched configuration that configures which resources should get "exclusivity" by default. I will try to find that issue and link it here.
