### ISSUE TITLE
Jobspec exception error with Kubernetes integration

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#472]
From @cmisale:

> yesterday I was working on (kind of automatically) creating a yaml file with the pods requirements of a simple pod I want to schedule.
The pod specs are sent by the management level (I'll find another name at some point) to the flux-resourcequery pod, by mean of gRPC messages.
I am partially recycling the yaml spec of an existing jobspec (basics/test001.yaml) and adding cpu, memory and gpu requirements I specify for the pod.
The yaml file I produce is this one:

```yaml
version: 1
resources:
type: node
count: 1
with:
- type: slot
count: 1
label: default
with:
- type: socket
count: 1
with:
- type: core
count: 2
- type: memory
count: 400
- type: gpu
count: 1
attributes:
system:
duration: 3600
tasks:
- command: busybox
slot: default
count:
per_slot: 1
```

> I assume it is at least partially correct. Not sure if the list of types (core, memory and gpu) is correct that way, but I saw in the resource-query code that I might have back a syntax error or similar, if the yaml spec is wrong.

> I save it in the same folder where test001.yaml file is. I am able to read it both from the code (just to check..), and also doing a cat of the file in the pod running on kubernetes.
I get this error fromcmd_match function. 
ERROR: Exception occurs for input file I/Obasic_ios::clear
The request I ask is allocate. I understand it has problems reading the file, but I don't understand what's the problem. In general, test001.yaml is read with no problems.
There's something that comes in your mind?

**Comment by dongahn** [comment]
@cmisale:

The exception is caught at https://github.com/flux-framework/flux-sched/blob/a3dcb3d5dc72a9338f5c7af8f40e1ee06912f38a/resource/utilities/command.cpp#L173

It was probably thrown at or around

https://github.com/flux-framework/flux-sched/blob/a3dcb3d5dc72a9338f5c7af8f40e1ee06912f38a/resource/utilities/command.cpp#L144

**Comment by dongahn** [comment]
Please make sure you give the correct path to the path to your jobspec file. (Try absolute path with the `match allocate` command.)

**Comment by dongahn** [comment]
Once you pass this issue, though, you will likely to hit jobspec parse errors. I used your jobspec file verbatim with `resource-query` using `tiny.graphml` GRUG file and I got the following error:

```console
ahn1@64643a7dc352:/usr/src/resource/utilities$ ./resource-query -G ../../t/data/resource/grugs/tiny.graphml
INFO: Loading a matcher: CA
resource-query> match allocate t.yaml
ERROR: Jobspec error for 1: yaml-cpp: error at line 15, column 1: end of map not found
```

So I rewrote your job spec as:

```yaml
version: 1
resources:
  - type: node
    count: 1
    with:
      - type: slot
        count: 1
        label: default
        with:
          - type: socket
            count: 1
            with:
              - type: core
                count: 2
              - type: memory
                count: 1
              - type: gpu
                count: 1

attributes:
  system:
    duration: 3600
tasks:
  - command: busybox
    slot: default
    count:
       per_slot: 1
```

```console
ahn1@64643a7dc352:/usr/src/resource/utilities$ ./resource-query -G ../../t/data/resource/grugs/tiny.graphml --match-format=pretty_simple
INFO: Loading a matcher: CA
resource-query> match allocate t1.yaml
      ---tiny0[1:shared]
      ------rack0[1:shared]
      ---------node1[1:shared]
      ------------socket1[1:exclusive]
      ---------------memory7[2:exclusive]
      ---------------gpu1[1:exclusive]
      ---------------core35[1:exclusive]
      ---------------core34[1:exclusive]
INFO: =============================
INFO: JOBID=1
INFO: RESOURCES=ALLOCATED
INFO: SCHEDULED AT=Now
INFO: =============================
```

Two things to notice.

- Use of indentations
- Memory request is 1, and this is interpreted as 1GB because `tiny.yaml` models each allocatable memory chunk as a pool of 1GB memory and the system has 2 of such pools.

```xml
        <node id="memory">
            <data key="type">memory</data>
            <data key="basename">memory</data>
            <data key="size">2</data>
            <data key="unit">GB</data>
        </node>
```

Flux's resource model has the concept of resource pool so that you can dial up and down the granularity of allocatable resources. For example, =if you want more fine grained memory granularity, you can increase the size and decrease the unit fields. 

Please refer to [RFC 4 resource model](https://github.com/flux-framework/rfc/blob/master/spec_4.adoc)
