### ISSUE TITLE
SNL: a suboptimal schedule observed with EASY

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#572]
I have been spending some time to understand a suboptimal schedule with the EASY backfill policy as reported by @amagela. While in the end I determined that this was the correct scheduler behavior, I thought it makes sense to leave our correspondences as a future reference for others to encounter.   

From @amagela
>The queue policy option (EASY) appears to still do FCFS. The script I ran is below and that is the order that it ran things. Thoughts? It ran it in 8 waves when it could've done it in 7.
 
```
flux mini submit -N1 -n  36 ./mpi_hello
flux mini submit -N1 -n  36 ./mpi_hello
flux mini submit -N2 -n  72 ./mpi_hello
flux mini submit -N1 -n  36 ./mpi_hello
flux mini submit -N1 -n  36 ./mpi_hello
flux mini submit -N1 -n  36 ./mpi_hello
flux mini submit -N1 -n  36 ./mpi_hello
flux mini submit -N1 -n  36 ./mpi_hello
flux mini submit -N1 -n  36 ./mpi_hello
flux mini submit -N1 -n  36 ./mpi_hello
flux mini submit -N1 -n  36 ./mpi_hello
flux mini submit -N4 -n 144 ./mpi_hello
flux mini submit -N3 -n 108 ./mpi_hello
flux mini submit -N2 -n  72 ./mpi_hello
flux mini submit -N2 -n  72 ./mpi_hello
flux mini submit -N2 -n  72 ./mpi_hello
flux mini submit -N3 -n 108 ./mpi_hello
```
 
```
$ printenv | grep -i flux
MANPATH=/hpcart/flux/install-lynx/share/man:/opt/openmpi/1.10/gnu/man:/opt/openmpi/1.10/gnu/share/man:/opt/rh/devtoolset-8/root/usr/share/man:/usr/share/lmod/lmod/share/man
FLUX_MODULE_PATH=/hpcart/flux/install-lynx/lib/flux/modules
FLUX_QMANAGER_OPTIONS=queue-policy=easy
FLUX_SEC_DIRECTORY=/ascldap/users/amagela/.flux
FLUX_CONNECTOR_PATH=/hpcart/flux/install-lynx/lib/flux/connectors
PATH=/hpcart/flux/install-lynx/bin:/opt/openmpi/1.10/gnu/bin:/opt/rh/devtoolset-8/root/usr/bin:/ascldap/users/amagela/bin:/usr/lib64/qt-3.3/bin:/usr/lpp/mmfs/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
FLUX_PMI_LIBRARY_PATH=/hpcart/flux/install-lynx/lib/flux/libpmi.so
PWD=/hpcart/flux/present
LUA_PATH=/hpcart/flux/install-lynx/share/lua/5.1/?.lua;;;
LUA_CPATH=/hpcart/flux/install-lynx/lib/lua/5.1/?.so;;;
SLURM_SUBMIT_DIR=/hpcart/flux/present
FLUX_EXEC_PATH=/hpcart/flux/install-lynx/libexec/flux/cmd
FLUX_URI=local:///tmp/flux-BDnTFN/0/local
PYTHONPATH=/hpcart/flux/install-lynx/lib/flux/python2.7
```

From me:

> This is expected because the jobs submitted earlier will be scheduled first, and your sequence under EASY backfill should indeed result in the same job schedule as FCFS.

**Comment by dongahn** [comment]
From @amagela:

> If I re-shuffle those cases to submit largest-to-smallest, we are getting close. Here's what it did (in waves).
 
```
4
3 - 1
3 - 1
2 - 1  (this is the one that messed up)
2 - 2
2 - 1 - 1
1 - 1 - 1 - 1
1
```

From me:

> Yes, this is odd to me as well. One thing I noticed is that, though, you don’t specify the walltime (e.g., -t 30) for each job, which any back fill scheduler requires to be able to do backfilling. So in this case, our scheduler would have used the default system walltime so backfilling algorithm should still work although based on pretty rough walltime estimate. My initial suspicion was: because each job gets the exactly same walltime, even one second delay in jobs running in each wave can lead our scheduler not to be able to backfill. IOW, You can’t fit W walltime job into W-1 second slot, for example.
 
> However, I need to study this a bit further. When my first test isn’t a clear-cut whether it is the case or not. I will look at this a bit more. If this is indeed a bug, I will see if I can fix it. I will move this discussion to our GitHub issue tracker as well.
 
> In any case, testing the new software system by someone other than me is really helpful and thank you!

**Comment by dongahn** [comment]
I determined that the EASY algorithm works correctly and in fact your problem was exactly caused as I suspected.
 
> because each job gets the exactly same walltime, even one second delay in jobs running in each wave can lead our scheduler not to be able to backfill. IOW, You can’t fit W walltime job into W-1 second slot,
 
To confirm, I added a walltime for each submit as the following and reran the test:
 
```
1: flux mini submit -N4 -n 144 -t 80 ./mpi_hello
2: flux mini submit -N3 -n 108 -t 80 ./mpi_hello
3: flux mini submit -N3 -n 108 -t 80 ./mpi_hello
4: flux mini submit -N2 -n  72 -t 80 ./mpi_hello
5: flux mini submit -N2 -n  72 -t 80 ./mpi_hello
6: flux mini submit -N2 -n  72 -t 80 ./mpi_hello
7: flux mini submit -N2 -n  72 -t 80 ./mpi_hello
8: flux mini submit -N1 -n  36 -t 70 ./mpi_hello
9: flux mini submit -N1 -n  36 -t 65 ./mpi_hello
10: flux mini submit -N1 -n  36 -t 60 ./mpi_hello
11: flux mini submit -N1 -n  36 -t 55 ./mpi_hello
12: flux mini submit -N1 -n  36 -t 50 ./mpi_hello
13: flux mini submit -N1 -n  36 -t 45 ./mpi_hello
14: flux mini submit -N1 -n  36 -t 40 ./mpi_hello
15: flux mini submit -N1 -n  36 -t 35 ./mpi_hello
16: flux mini submit -N1 -n  36 -t 30 ./mpi_hello
17: flux mini submit -N1 -n  36 -t 25 ./mpi_hello
```
 
The schedule produced by our EASY backfill queuing policy now solves the issue you noticed: all the jobs completed in 7 waves.
 
```
1: Started at: Wed Jan 22 10:30:01 2020
8: Started at: Wed Jan 22 10:30:22 2020
2: Started at: Wed Jan 22 10:30:23 2020
9: Started at: Wed Jan 22 10:30:43 2020
3: Started at: Wed Jan 22 10:30:44 2020
10: Started at: Wed Jan 22 10:31:03 2020
11: Started at: Wed Jan 22 10:31:05 2020
4: Started at: Wed Jan 22 10:31:05 2020
15: Started at: Wed Jan 22 10:31:24 2020
16: Started at: Wed Jan 22 10:31:25 2020
5: Started at: Wed Jan 22 10:31:26 2020
6: Started at: Wed Jan 22 10:31:46 2020
7: Started at: Wed Jan 22 10:31:48 2020
12: Started at: Wed Jan 22 10:32:07 2020
13: Started at: Wed Jan 22 10:32:07 2020
14: Started at: Wed Jan 22 10:32:08 2020
17: Started at: Wed Jan 22 10:32:08 2020
```
 
IOW, in your notation
 
```
4
3 - 1
3 - 1
2 - 1 - 1
2 - 1 - 1
2 - 2
1 - 1 - 1 - 1
```
 
It may appear odd that job 15 and 16 are backfilled before 12 – 17. But it actually tells about the original issue. When the jobs are allocated and reserved (for backfilling), the gaps can be created in real time such a way that they can be much smaller than the theoretical schedule we would create in a paper.

**Comment by dongahn** [comment]
The smallest reproducer I was able to create was:

```shell
#!/bin/sh
set -x

jobid=$(flux job submit N3.yaml)

nextid=$(flux job submit N2.yaml)
jobid+=" ${nextid}"

nextid=$(flux job submit N2.yaml)
jobid+=" ${nextid}"

nextid=$(flux job submit N2.yaml)
jobid+=" ${nextid}"

nextid=$(flux job submit N2.yaml)
jobid+=" ${nextid}"

nextid=$(flux job submit N1.yaml)
jobid+=" ${nextid}"

nextid=$(flux job submit N1.yaml)
jobid+=" ${nextid}"

nextid=$(flux job submit N1.yaml)
jobid+=" ${nextid}"

echo $jobid
for job in ${jobid};
do
    echo $job
    flux job wait-event ${job} finish
    flux job attach $job >> job.attach.out
done
```

Resource section for N1, N2, and N3 are:
```yaml
  "resources": [
    {
      "count": 1,
      "with": [
        {
          "count": 36,
          "with": [
            {
              "count": 1,
              "type": "core"
            }
          ],
          "type": "slot",
          "label": "task"
        }
      ],
      "type": "node"
    }
  ]
```

```yaml
  "resources": [
    {
      "count": 2,
      "with": [
        {
          "count": 36,
          "with": [
            {
              "count": 1,
              "type": "core"
            }
          ],
          "type": "slot",
          "label": "task"
        }
      ],
      "type": "node"
    }
  ]
```

```yaml
  "resources": [
    {
      "count": 3,
      "with": [
        {
          "count": 36,
          "with": [
            {
              "count": 1,
              "type": "core"
            }
          ],
          "type": "slot",
          "label": "task"
        }
      ],
      "type": "node"
    }
  ]
```

And the walltime for a single node job is 25 secs and other jobs are 60 secs.

Running this with 4-node Flux instance,

```console
rztopaz578{dahn}38: cat job.attach.out | grep Started | awk '{print NR ": " $s}' | sort -k 6
6: Started at: Wed Jan 22 09:58:08 2020
1: Started at: Wed Jan 22 09:58:09 2020
7: Started at: Wed Jan 22 09:58:28 2020
2: Started at: Wed Jan 22 09:58:30 2020
3: Started at: Wed Jan 22 09:58:49 2020
4: Started at: Wed Jan 22 09:58:51 2020
5: Started at: Wed Jan 22 09:59:10 2020
8: Started at: Wed Jan 22 09:59:12 2020
```

Notice that when 3-node job (job 6) completes, only one 2-node job and one 1-node job is scheduled in the second wave.
