### ISSUE TITLE
resource: multiple top-level resource requests

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#580]
Does the resource matching service currently support multiple top-level resource requests - that is multiple resource roots?  As a concrete example:

```yaml
resources:
  - type: node
    count: 4
    with:
      - type: slot
        count: 1
        label: default
        with:
          - type: core
            count: 2
  - type: license
    count: 4
```

CC @dongahn and @milroy who are probably closest to the code and most likely to know off the top of their heads.

**Comment by dongahn** [comment]
Yap, this should be supported though we should test it.

**Comment by dongahn** [comment]
I spoke too soon. 

I think the current code will assume there is a common prefix leading to both node and license vertices and do the match. I ran resource-query with it which behaved a bit odd without having a common slot that contains both node and license. 

If you have a specific use case, could you elaborate. Need to break down matching issues and tackle one by one at this point.

**Comment by SteVwonder** [comment]
Yeah. The use-case is a tiered storage one. Assume you have a pool of storage somewhere that isn’t node local (could be a pool on the cluster network or out on the file system network), and you want to request capacity on that in addition to requesting compute nodes. 

Here is a modified example from this issue: https://github.com/flux-framework/rfc/issues/204

```yaml
resources:
  - type: node
    count: 4
    with:
      - type: slot
        count: 1
        label: default
        with:
          - type: core
            count: 2
  - type: storage
    count: 4
    unit: terabytes
    label: PFS-cache
```
