### ISSUE TITLE
Need a more user-friendly configuration scheme for qmanager

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#650]
From PR #649 and PR #645.

**Comment by dongahn** [comment]
From PR #649:

> As we discussed before, I'm not entirely happy with the current
way of configuring queues. But I thought there is a benefit of getting
the runtime logic correct as soon as possible and then improve
upon user friendliness later.

To be more specific: it was much easier to implement and reason about multi-queue specifications when the configuration file and module load options were identical  (current implementation). Once we make sure everything is correct and performant under the current implementation, ways to specify multi-queue can diverge. 

For example, configuration file become more user friendly while load option specification stays the same.

For configuration file, I am thinking along the line of:

```toml
[qmanager]

# default if per-queue doesn't specify 
queue-policy = "fcfs"
queue-params = "queue-depth=512"

    [batch]
    queue-policy = "conservative"

    [debug]
    queue-depth = 32

    [all]

```
 
Internally, once the toml file is parsed, `qmanager_opts` would transform this form into the module load option form to process. This way, there is only one logic that provides a semantics for both conf file and load options.

Doing all of this at the same time focusing on the core multi-queue support was too time consuming and involved. (Too big of change as a single PR.)
