### ISSUE TITLE
t/data/resource/jobspecs: some jobspecs that are self-described as V1 aren't V1

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#688]
For example, the `basics/test009.yaml` is not valid V1 jobspec because it requests a `socket` under `slot` rather than `core` or `gpu`, but it is self described as version 1:

```yaml
version: 1
resources:
  - type: node
    count: 1
    with:
      - type: slot
        count: 2
        label: default
        with:
          - type: socket
            count: 1

# a comment
attributes:
  system:
    duration: 3600
tasks:
  - command: [ "app" ]
    slot: default
    count:
      per_slot: 1
```

This particular example should actually be jobspec version 2.  As noted in #679, this change can probably wait until we support Jobspec V2 more fully.
