### ISSUE TITLE
resource: segfault during match of multi-socket jobspec on Corona

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#709]
Using flux-sched v0.10.0 built from source with the docker-run-checks.sh script based on the `focal` image.

I encounter a segfault when querying a multi-socket jobspec using resource-query against a single-node hwloc of Corona:
```
erbein1@94f9c9953c87:/usr/src/t$ gdb --args ../resource/utilities/resource-query -L /usr/src/t/data/hwloc-data/001N/amd_gpu/corona11.xml -f hwloc -W node,socket,core -S CA -P low
<snip>
(gdb) r
Starting program: /usr/src/resource/utilities/resource-query -L /usr/src/t/data/hwloc-data/001N/amd_gpu/corona11.xml -f hwloc -W node,socket,core -S CA -P low
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
INFO: Loading a matcher: CA
resource-query> match allocate /usr/src/t/data/resource/jobspecs/node_local_storage/corona.yaml

Program received signal SIGSEGV, Segmentation fault.
0x000055de0d731e25 in Flux::resource_model::detail::dfu_impl_t::dom_slot (this=<optimized out>, meta=..., u=<optimized out>, slot_shape=..., pristine=<optimized out>, excl=<optimized out>, dfu=...) at traversers/dfu_impl.cpp:513
513                     eval_edg_t ev_edg ((*egroup_i).edges[0].count,
(gdb) bt
#0  0x000055de0d731e25 in Flux::resource_model::detail::dfu_impl_t::dom_slot (this=<optimized out>, meta=..., u=<optimized out>, slot_shape=..., pristine=<optimized out>, excl=<optimized out>, dfu=...) at traversers/dfu_impl.cpp:513
#1  0x000055de0d730c7e in Flux::resource_model::detail::dfu_impl_t::dom_dfv (this=<optimized out>, meta=..., u=<optimized out>, resources=std::vector of length 1, capacity 1 = {...}, pristine=<optimized out>, excl=0x7ffe9575363f,
    to_parent=...) at traversers/dfu_impl.cpp:554
#2  0x000055de0d7312e6 in Flux::resource_model::detail::dfu_impl_t::explore (this=<optimized out>, meta=..., u=<optimized out>, subsystem=..., resources=..., pristine=<optimized out>, excl=<optimized out>, direction=<optimized out>,
    dfu=...) at traversers/dfu_impl.cpp:387
#3  0x000055de0d731b91 in Flux::resource_model::detail::dfu_impl_t::dom_exp (this=this@entry=0x55de0ebb3920, meta=..., u=u@entry=0, resources=std::vector of length 1, capacity 1 = {...}, pristine=true, excl=excl@entry=0x7ffe95753ad1,
    dfu=...) at traversers/dfu_impl.cpp:448
#4  0x000055de0d730948 in Flux::resource_model::detail::dfu_impl_t::dom_dfv (this=<optimized out>, meta=..., u=<optimized out>, resources=std::vector of length 1, capacity 1 = {...}, pristine=<optimized out>, excl=0x7ffe95753bb2,
    to_parent=...) at traversers/dfu_impl.cpp:556
#5  0x000055de0d734cd8 in Flux::resource_model::detail::dfu_impl_t::select (this=this@entry=0x55de0ebb3920, j=..., root=root@entry=0, meta=..., excl=excl@entry=false) at traversers/dfu_impl.cpp:884
#6  0x000055de0d72ba60 in Flux::resource_model::dfu_traverser_t::schedule (this=0x55de0ebb3920, jobspec=..., meta=..., x=<optimized out>, op=Flux::resource_model::match_op_t::MATCH_ALLOCATE, root=0,
    dfv=std::unordered_map with 1 element = {...}) at traversers/dfu.cpp:60
#7  0x000055de0d72c68e in Flux::resource_model::dfu_traverser_t::run (this=<optimized out>, jobspec=..., writers=std::shared_ptr<Flux::resource_model::match_writers_t> (use count 1, weak count 0) = {...},
    op=op@entry=Flux::resource_model::match_op_t::MATCH_ALLOCATE, jobid=jobid@entry=1, at=at@entry=0x7ffe95753f68) at traversers/dfu.cpp:258
#8  0x000055de0d723a84 in Flux::resource_model::cmd_match (ctx=std::shared_ptr<Flux::resource_model::resource_context_t> (use count 1, weak count 0) = {...}, args=std::vector of length 3, capacity 4 = {...})
    at /usr/include/c++/9/bits/shared_ptr_base.h:1020
#9  0x000055de0d6fc37d in control_loop (ctx=...) at resource-query.cpp:447
#10 main (argc=<optimized out>, argv=<optimized out>) at resource-query.cpp:743
```

The jobspec:
```yaml
version: 1
resources:
  - type: node
    count: 1
    with:
      - type: slot
        label: default
        count: 1
        with:
          - type: socket
            count: 1
            with:
              - type: core
                count: 24
          - type: socket
            count: 1
            with:
              - type: core
                count: 24

# a comment
attributes:
  system:
    duration: 57600
tasks:
  - command: [ "default" ]
    slot: default
    count:
      per_slot: 1
```

**Comment by SteVwonder** [comment]
At first glance, the provided jobspec looks silly.  Why not just up the count to `2` and remove the extra child?  The actual jobspec that I tried was more like:

```yaml
      - type: slot
        label: default
        count: 1
        with:
          - type: socket
            count: 1
            with:
              - type: core
                count: 24
              - type: storage
                count: 1500
          - type: socket
            count: 1
            with:
              - type: core
                count: 24
```

Since NVMe drives are connected via PCI, there is one socket that technically is "closer" than the other.  But the original posted jobpsec is simpler and fails on existing hwloc xml.
