### ISSUE TITLE
Resource Query cannot satisfy MTL Storage Jobspec with both mtl1unit and mtl2unit requests

### ISSUE THREAD

**Issue by Keith-Bateman** [flux-framework/flux-sched#853]
If we use the default policies for resource-query on a multi-tiered grug (such as mtl3) and try to match a jobspec that requests SSDs through mtl1unit and mtl2unit simultaneously, we get a result that the request is unsatisfiable with no matching resources found, even though requesting mtl1unit SSDs or mtl2unit SSDs separately would work.
An example of a jobspec that fits this description for the mtl3 graph would be:
```yaml
version: 9999
resources:
  - type: rack
    count: 1
    with:
      - type: node
        count: 1
        with:
          - type: slot
            label: default
            count: 1
            with:
              - type: socket
                count: 1
                with:
                  - type: core
                    count: 18
      - type: mtl1unit
        count: 1
        with:
          - type: ssd
            count: 512
            exclusive: true
  - type: mtl2unit
    count: 1
    with:
      - type: mtl1unit
        count: 1
        with:
          - type: ssd
            count: 512
            exclusive: true
# a comment
attributes:
  system:
    duration: 3600
tasks:
  - command: [ "default" ]
    slot: default
    count:
      per_slot: 1
```
[testdana.yaml.txt](https://github.com/flux-framework/flux-sched/files/6813708/testdana.yaml.txt)
