### ISSUE TITLE
support TOML queue configuration described in RFC 33

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#950]
Problem: fluxion queues are currently configured on the `qmanager` command line as in `t1006-qmanager-multiqueue.t`, but a framework wide queue TOML configuration was proposed in [RFC 33](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_33.html).

The RFC 31 style configuration will need to be implemented in fluxion.

**Comment by garlick** [comment]
For a workaround, the qmanager module command line options also work from TOML, e.g.

```toml
[sched-fluxion-qmanager]
queues = "batch debug"
queue-policy-per-queue="batch:easy debug:fcfs"
```

If we initially require queues to be configured both here and in flux-core, we can get queues working without modifying fluxion.

**Comment by garlick** [comment]
In the meeting today we discussed whether we should try to do this in the context of the `qmanager_opts_t` class or use the C approach used throughout flux-core, the gist of which is
- call `flux_get_conf (h)` to get the broker "config object", a `flux_conf_t`
- unpack what you need, for example the "queues" table as a jansson json object, with `flux_conf_unpack()`
- continue to parse using regular jansson tools
- for extra credit (probably not needed here) you can implement the `config-reload` RPC handler to allow the config to be changed on the fly

Here's a simple [simple example with no reload](https://github.com/flux-framework/flux-core/blob/937e84fa339073883124e0bddfabf2f0fcaf02eb/src/modules/job-exec/job-exec.c#L1160

[RFC 33](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_33.html) defines the [queues] table and the global and per-queue [policy] tables.

To get the list of queues, you would just get the list of keys in the [queues] table.

We haven't used the "scheduler" policy key yet but it's here to support scheduler-specific stuff like the easy/fcfs in the example above.  The global value would be in the [policy] table, while the per-queue values would be in the [queues] table, under each queue name, e.g.
```toml
[policy]
scheduler.queue-policy = "fcfs"

[queues.batch]
policy.scheduler.queue-policy = "easy"

[queues.debug]
# Use the default fcfs
```
(I made up the `queue-policy` key name.  This name space is owned by the scheduler so feel free to ad lib).

p.s.  ping to @milroy per request
