### ISSUE TITLE
-o gpu-affinity=per-task choosing 'wrong' gpus on tioga

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-sched#986]

**Comment by grondo** [comment]
Transferred this issue to flux-sched since it is the thing assigning GPUs in this case.

**Comment by milroy** [comment]
I investigated the behavior of `hwloc` on the Tioga system to see if and how it can generate an XML that can be loaded by the Fluxion `resource-query` utility. With `resource-query` I tested whether Fluxion can generate a mapping that takes into account CPU-GPU locality. 

First some background. On tioga, `lstopo` (based on`hwloc` 2.1.9) returns a warning indicating that it is ignoring invalid hardware topology. The resulting XML file has the GPUs hanging off by themselves underneath the node. To detect the topology correctly, you need to set `HWLOC_COMPONENTS=x86` in the environment:
```bash

[milroy1@tioga11:~]$ lstopo
Machine (503GB total)
  Package L#0
    Group0 L#0
      NUMANode L#0 (P#0 125GB)
      L3 L#0 (32MB)
        L2 L#0 (512KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0 + PU L#0 (P#0)
        L2 L#1 (512KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1 + PU L#1 (P#1)
        L2 L#2 (512KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2 + PU L#2 (P#2)
        L2 L#3 (512KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3 + PU L#3 (P#3)
        L2 L#4 (512KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4 + PU L#4 (P#4)
        L2 L#5 (512KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5 + PU L#5 (P#5)
        L2 L#6 (512KB) + L1d L#6 (32KB) + L1i L#6 (32KB) + Core L#6 + PU L#6 (P#6)
        L2 L#7 (512KB) + L1d L#7 (32KB) + L1i L#7 (32KB) + Core L#7 + PU L#7 (P#7)
        HostBridge
          PCIBridge
            PCI d1:00.0 (Display)
              GPU(RSMI) "rsmi4"
[...]
```
Loading the corresponding XML file works as expected with `resource-query`:
```bash

$ ./resource-query -L test.xml -f hwloc
resource-query> find status=up
[...]
      ---------------L3cache6[32768:x]
      ---------------------pu56[1:x]
      ------------------core56[1:x]
      ---------------------pu57[1:x]
      ------------------core57[1:x]
      ---------------------pu58[1:x]
      ------------------core58[1:x]
      ---------------------pu59[1:x]
      ------------------core59[1:x]
      ---------------------pu60[1:x]
      ------------------core60[1:x]
      ---------------------pu61[1:x]
      ------------------core61[1:x]
      ---------------------pu62[1:x]
      ------------------core62[1:x]
      ---------------------pu63[1:x]
      ------------------core63[1:x]
      ------------------gpu1[1:x]
      ---------------L3cache7[32768:x]
      ---------------numanode3[1:x]
      ------------group3[1:x]
      ---------socket0[1:x]
      ---------storage13[52:x]
      ---------storage14[52:x]
      ------tioga11[1:x]
      ---cluster0[1:x]
INFO: =============================
INFO: EXPRESSION="status=up"
INFO: =============================
```
But there's a lot more detail in the graph and hence number of resource vertices than can be represented by a jobspec generated from, e.g., `flux run -N1 -c4 -n1 -g4 -o cpu-affinity=per-task -o gpu-affinity=per-task sleep 2`: 
```JSON
{
  "resources": [
    {
      "type": "node",
      "count": 1,
      "with": [
        {
          "type": "slot",
          "count": 1,
          "with": [
            {
              "type": "core",
              "count": 4
            },
            {
              "type": "gpu",
              "count": 4
            }
          ],
          "label": "task"
        }
      ]
    }
  ],
  "tasks": [
    {
      "command": [
        "sleep",
        "2"
      ],
      "slot": "task",
      "count": {
        "per_slot": 1
      }
    }
  ],
  "attributes": {
    "system": {
      "duration": 0,
      "cwd": "/g/g12/milroy1/git/flux-sched/resource/utilities",
      "shell": {
        "options": {
          "rlimit": {
            "cpu": -1,
            "fsize": -1,
            "data": -1,
            "stack": -1,
            "core": 16384,
            "nofile": 128000,
            "as": -1,
            "rss": -1,
            "nproc": 8192
          },
          "cpu-affinity": "per-task",
          "gpu-affinity": "per-task"
        }
      }
    }
  },
  "version": 1
}
```
This means that Fluxion won't return a match (converted to YAML): 
```bash
resource-query> match allocate jobspec.yaml
INFO: =============================
INFO: No matching resources found
INFO: JOBID=1
INFO: =============================
```
However, a jobspec like this will work:
```YAML
version: 1
resources:
  - type: slot
    count: 1
    with:
    - type: group
      count: 4
      with:
       - type: cache
         count: 65536
         with:
          - type: gpu
            count: 1
    label: task
tasks:
- command:
  - sleep
  - '2'
  slot: task
  count:
    per_slot: 1
attributes:
  system:
    duration: 0
    cwd: ""
    shell:
      options:
        rlimit:
          cpu: -1
          fsize: -1
          data: -1
          stack: -1
          core: 16384
          nofile: 128000
          as: -1
          rss: -1
          nproc: 8192
        cpu-affinity: per-task
        gpu-affinity: per-task
```
Which produces the following mapping:
```bash
resource-query> match allocate jobspec.yaml
      ------------------gpu4[1:x]
      ---------------L3cache0[32768:x]
      ------------------gpu5[1:x]
      ---------------L3cache1[32768:x]
      ------------group0[1:x]
      ------------------gpu2[1:x]
      ---------------L3cache2[32768:x]
      ------------------gpu3[1:x]
      ---------------L3cache3[32768:x]
      ------------group1[1:x]
      ------------------gpu6[1:x]
      ---------------L3cache4[32768:x]
      ------------------gpu7[1:x]
      ---------------L3cache5[32768:x]
      ------------group2[1:x]
      ------------------gpu0[1:x]
      ---------------L3cache6[32768:x]
      ------------------gpu1[1:x]
      ---------------L3cache7[32768:x]
      ------------group3[1:x]
      ---------socket0[1:s]
      ------tioga11[1:s]
      ---cluster0[1:s]
INFO: =============================
INFO: JOBID=1
INFO: RESOURCES=ALLOCATED
INFO: SCHEDULED AT=Now
INFO: =============================
```
Note the mapping group0 --> GPU4,5, group1 --> GPU2,3, group2 --> GPU6,7, group3 --> GPU0,1.

**Comment by milroy** [comment]
To clarify above, the jobspec I listed requests four "groups" (should they be discovered as sockets?) each with two GPUs to illustrate the mapping @ryanday36 reported in the first comment. To get the desired resources corresponding to the `flux run` command above, I'd need this:
```YAML
version: 1
resources:
  - type: node
    count: 1
    with:
     - type: socket
       count: 1
       with:
        - type: slot
          label: task
          count: 1
          with:
           - type: group
             count: 4
             with:
              - type: cache
                count: 32768
                with:
                 - type: gpu
                   count: 1
tasks:
- command:
  - sleep
  - '2'
  slot: task
  count:
    per_slot: 1
attributes:
  system:
    duration: 0
    cwd: ""
    shell:
      options:
        rlimit:
          cpu: -1
          fsize: -1
          data: -1
          stack: -1
          core: 16384
          nofile: 128000
          as: -1
          rss: -1
          nproc: 8192
        cpu-affinity: per-task
        gpu-affinity: per-task
```
Note the ugliness with handling the cache count.
