### ISSUE TITLE
Deferred allocation

### ISSUE THREAD

**Issue by JaeseungYeom** [flux-framework/flux-sched#987]
Problem: support a scheduling request for an allocation to occur at a specific time in the future.

Currently, a reservation of resources occurs as early as possible. However, for supporting workflows that benefit from running tasks across heterogeneous platforms, it is desired to synchronize multiple allocations across different child instances. Such that task 1-10 run on corona while task 11-20 "simultaneously" run on another cluster managed by Flux.
To support such use cases, two things are needed.
One is the deferred allocation capability, and the other is a means to query the allocation delay.
A parent instance can query its remote child instances to find out when is the earliest by which all the children can allocate requested resources. Then, it should be possible to allocate synchronously across instances.

Pushing the reservation time back should also consider back-filing.
To be clear, this is not the same as to try allocating at the earliest after a specific point in time.
I am not entirely sure if the existing issue #963 is the latter case or the same as this.

**Comment by milroy** [comment]
> A parent instance can query its remote child instances to find out when is the earliest by which all the children can allocate requested resources. Then, it should be possible to allocate synchronously across instances.

To make sure I understand the basics (without getting into too much complexity yet) of the deferred allocation capability, this is a three-part process: 
1) submit the jobspecs to all child instances with a new `match_reserve (jobspec)` request that reserves the requested resources on each child instance at the earliest time possible and return those times. 
2) Find the latest time returned (T), and for all the child instances that returned earlier times, issue a new `match_reserve_at (jobspec, T)` which moves the reservation back to time T. 
3) Handle the case where one or more children can't satisfy `match_reserve_at (jobspec, T)`. 

Is that basically correct?

**Comment by milroy** [comment]
I've confirmed that by manipulating the `at` time in `dfu_traverser_t::run`: https://github.com/flux-framework/flux-sched/blob/35d3c96bb7378ec4f6803a7e340043fd4040e8c1/resource/traversers/dfu.cpp#L277 we can achieve the desired behavior. Here I've simulated this by hardcoding `at = 3600` in `dfu_traverser_t::run` and performing a `match allocate`:

```bash
resource-query> match allocate t/data/resource/jobspecs/basics/test001.yaml
      ---------------core35[1:x]
      ------------socket1[1:x]
      ---------node1[1:s]
      ------rack0[1:s]
      ---tiny0[1:s]
INFO: =============================
INFO: JOBID=1
INFO: RESOURCES=RESERVED
INFO: SCHEDULED AT=3600
INFO: =============================
``` 

Of course, there will be a decent amount of development required to add new `match_op_t` cases and determine the best way to include the desired time in the jobspec.

**Comment by milroy** [comment]
> Of course, there will be a decent amount of development required to add new match_op_t cases

Actually that is not complicated. 

> and determine the best way to include the desired time in the jobspec.

As discussed with @grondo during last week's team meeting, we still need to decide how to proceed with this part. The current state of PR #1013 uses the optional `system` key space to let users set the deferred time. To ensure the allocation doesn't get moved up (which is undesired) or moved back for each `match allocate_orelse_reserve`, I added code to use a base time (`deferred_from` in epoch seconds) which makes `deferred_start` a relative time: https://github.com/flux-framework/flux-sched/blob/90f822967c30ec6d3d692e85bd39241a516c2abd/resource/traversers/dfu_impl.hpp#L104

An example test jobspec looks like this:

```yaml
version: 9999
resources:
    - type: cluster
      count: 1
      with:
        - type: rack
          count: 1
          with:
            - type: node
              count: 1
              with:
                  - type: slot
                    count: 1
                    label: default
                    with:
                      - type: socket
                        count: 1
                        with:
                          - type: core
                            count: 1
# a comment
attributes:
  system:
    duration: 3600
    # optional deferred keys
    deferred_start: 1800
    deferred_from: 0
tasks:
  - command: [ "app" ]
    slot: default
    count:
      per_slot: 1
```

My sense is that while this may work well for automated submission it will be hard for manual submission. @jameshcorbett and @ryanday36 might have good input here.
